name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Node.js and Yarn versions
        run: |
          node --version
          yarn --version

      - name: List Installed Dependencies
        run: yarn list

      - name: Run Unit Tests
        run: yarn test --verbose